version: '3.5'
services:
    # mysql:
    #     hostname: db
    #     image: 'mariadb:10.3'
    #     restart: always
    #     volumes:
    #         - './mysql/data:/var/lib/mysql'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_USER: '${DB_USERNAME}'
    #         MYSQL_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_DATABASE: '${DB_DATABASE}'
    #     networks:
    #         elk-network:
    #             aliases:
    #                 - db

    elasticsearch:
        build: elasticsearch/
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            ES_JAVA_OPTS: '-Xmx1g -Xms1g'
        networks:
            elk-network:
                aliases:
                    - elasticsearch
    logstash:
        build: logstash/
        volumes:
            - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
            - './logstash/pipeline:/usr/share/logstash/pipeline'
            - './logstash/lastrun:/root/.logstash_jdbc_last_run'
        ports:
            - '5000:5000'
        environment:
            LS_JAVA_OPTS: '-Xmx1g -Xms1g'
        env_file:
            - .env
        networks:
            - elk-network
        depends_on:
            - elasticsearch
    kibana:
        build: kibana/
        volumes:
            - './kibana/config/:/usr/share/kibana/config'
        ports:
            - '5601:5601'
        networks:
            - elk-network
        depends_on:
            - elasticsearch

networks:
    elk-network:
        driver: bridge
